### ISSUE TITLE
store and load MeetingList and TeamMemberList

### ISSUE THREAD

**Issue by lowxizhi** [AY1920S2-CS2113T-T12-1/tp#42]
call updateMasterSchedule() when loading MeetingList

**Comment by synCKun** [comment]
Issue:
When MeetingList is first loaded by the `loadListFromData()` function in our main class's constructor, you're asking that i call `updateMasterSchedule()`. However, in `MeetingOrganizer.run()`, user's input will overwrite `Boolean[][] masterSchedule` due to its constructor being called, thus undoing what we did.

Suggestion:
i will implement code to load list of members with their respective schedule from *data* (in addition to current list of scheduled meetings) and call `new ScheduleHandler(ArrayList<TeamMember> teamMemberList);` to rebuild masterSchedule in ScheduleHandler class, all in the constructor of our main class.

Required action by @MeLoveCarbs 
change code in `MeetingOrganizer.run()` so that new user inputs will not overwrite data loaded from *data*, and allow input of member's name

**Comment by MeLoveCarbs** [comment]
Could you change it? Not sure what part of the code logic you're mentioning @synCKun
